import Head from 'next/head';
import '../styles/globals.css';
import wrapper from '../redux/reducers/configureStore';
import { createTheme, ThemeProvider } from '@mui/material/styles';
import UserPermissionComponent from '../redux/dispatch_component/UserPermissionComponent';
import WorkspacePermissionComponent from '../redux/dispatch_component/WorkspacePermissionComponent';
import Router from 'next/router';

/**
 * 메인 컬러 : #344b98;
 * 진진 파랑 : #2C73D2;
 * 진 파랑 : #309FFF;
 * 중간 파랑 : #609FFF;
 * 연 파랑 : #7DC2FF;
 * 핑크 : #db2e5e;
 * 그린 : #5fcf80;
 * 레드 : #e56767;
 * box-shadow: 1px 1px 10px 0 rgb(72 75 108 / 8%);
 * background: #f9fbfc;
 * modalCloseButtonColor:#959eae
 */
// == NProgress Module START ==
import NProgress from "nprogress";
import "nprogress/nprogress.css";
import { CustomToastContainer } from '../components/toast/custom-react-toastify/v1';
import { CustomDefaultBackdrop } from '../components/backdrop/default/v1';

const theme = createTheme();

Router.onRouteChangeStart = () => {
	NProgress.start();
}
Router.onRouteChangeComplete = () => {
	// console.log('onRouteChangeComplete triggered');
	NProgress.done();
};

Router.onRouteChangeError = () => {
	// console.log('onRouteChangeError triggered');
	NProgress.done();
};
// == NProgress Module END ==

function MyApp({ Component, pageProps }) {
	return (
		<>
			<Head>
				<title>셀러툴</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
				{/* GA 태그 추가 */}
				<script
					async
					src={`https://www.googletagmanager.com/gtag/js?id=G-3MNX1H7VPY`}
				></script>
				<script
					dangerouslySetInnerHTML={{
						__html: `
							window.dataLayer = window.dataLayer || [];
							function gtag(){dataLayer.push(arguments);}
							gtag('js', new Date());
							gtag('config', 'G-3MNX1H7VPY');
						`,
					}}
				></script>
			</Head>
			<UserPermissionComponent />
			<WorkspacePermissionComponent />
			<CustomToastContainer />
			<CustomDefaultBackdrop />
			<ThemeProvider theme={theme}>
				<Component {...pageProps} />
			</ThemeProvider>
		</>
	)
}

export default wrapper.withRedux(MyApp);
